# Generated by Django 6.0.6 on 2026-07-17 10:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("profiles", "0001_initial"),
        ("wagtailusers", "0015_userprofile_keyboard_shortcuts"),
    ]

    operations = [
        migrations.CreateModel(
            name="AdminProfileModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "language",
                    models.CharField(
                        choices=[("en", "English"), ("fr", "French"), ("ru", "Russia")],
                        default="ru",
                        max_length=10,
                    ),
                ),
                (
                    "time_zone",
                    models.CharField(default="Asia/Krasnoyarsk", max_length=50),
                ),
                (
                    "dashboard_preference",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="User preferences for dashboards and layout",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        db_comment="It is from the 'wagtail sers .models. UserProfile'",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="wagtailusers.userprofile",
                        verbose_name="User",
                    ),
                ),
            ],
            options={
                "verbose_name": "Admin profile",
                "verbose_name_plural": "Admin profiles",
                "db_table": "profiles_admin",
            },
        ),
        migrations.CreateModel(
            name="ClientProfileModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "language",
                    models.CharField(
                        choices=[("en", "English"), ("fr", "French"), ("ru", "Russia")],
                        default="ru",
                        max_length=10,
                    ),
                ),
                (
                    "time_zone",
                    models.CharField(default="Asia/Krasnoyarsk", max_length=50),
                ),
                (
                    "dashboard_preference",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="User preferences for dashboards and layout",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        db_comment="It is from the 'wagtail. users .models .UserProfile'",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="wagtailusers.userprofile",
                        verbose_name="User",
                    ),
                ),
            ],
            options={
                "verbose_name": "Client profile",
                "verbose_name_plural": "Client's profiles",
                "db_table": "profiles_client",
            },
        ),
        migrations.CreateModel(
            name="EditorProfileModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "language",
                    models.CharField(
                        choices=[("en", "English"), ("fr", "French"), ("ru", "Russia")],
                        default="ru",
                        max_length=10,
                    ),
                ),
                (
                    "time_zone",
                    models.CharField(default="Asia/Krasnoyarsk", max_length=50),
                ),
                (
                    "dashboard_preference",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="User preferences for dashboards and layout",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        db_comment="It is from the 'wagtail.users.models. UserProfile'",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="wagtailusers.userprofile",
                        verbose_name="User",
                    ),
                ),
            ],
            options={
                "verbose_name": "Editor profile",
                "verbose_name_plural": "Editor profiles",
                "db_table": "profiles_editor",
            },
        ),
        migrations.CreateModel(
            name="ManagerProfileModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "language",
                    models.CharField(
                        choices=[("en", "English"), ("fr", "French"), ("ru", "Russia")],
                        default="ru",
                        max_length=10,
                    ),
                ),
                (
                    "time_zone",
                    models.CharField(default="Asia/Krasnoyarsk", max_length=50),
                ),
                (
                    "dashboard_preference",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="User preferences for dashboards and layout",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        db_comment="It is from the 'wagtail.users.models. UserProfile'",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="wagtailusers.userprofile",
                        verbose_name="User",
                    ),
                ),
            ],
            options={
                "verbose_name": "Manager profile",
                "verbose_name_plural": "Manager profiles",
                "db_table": "profiles_manage",
            },
        ),
        migrations.CreateModel(
            name="ModeratorProfileModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "language",
                    models.CharField(
                        choices=[("en", "English"), ("fr", "French"), ("ru", "Russia")],
                        default="ru",
                        max_length=10,
                    ),
                ),
                (
                    "time_zone",
                    models.CharField(default="Asia/Krasnoyarsk", max_length=50),
                ),
                (
                    "dashboard_preference",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="User preferences for dashboards and layout",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        db_comment="It is from the 'wagtail users  UserProfile'",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="wagtailusers.userprofile",
                        verbose_name="User",
                    ),
                ),
            ],
            options={
                "verbose_name": "Moderator profile",
                "verbose_name_plural": "Moderator's profiles",
                "db_table": "profiles_moderator",
            },
        ),
        migrations.CreateModel(
            name="UserProfileManagerModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "admin",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profiles_admin",
                        related_query_name="profile",
                        to="profiles.adminprofilemodel",
                        verbose_name="Admin",
                    ),
                ),
                (
                    "client",
                    models.ForeignKey(
                        blank=True,
                        db_comment="User profile",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profiles",
                        related_query_name="profiles_client",
                        to="profiles.clientprofilemodel",
                        verbose_name="Client",
                    ),
                ),
                (
                    "editor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profiles_editor",
                        related_query_name="profile",
                        to="profiles.editorprofilemodel",
                        verbose_name="Editor",
                    ),
                ),
                (
                    "manager",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile_manager",
                        related_query_name="profile",
                        to="profiles.managerprofilemodel",
                        verbose_name="Manager",
                    ),
                ),
                (
                    "moderator",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile_moderator",
                        related_query_name="profile_moderator",
                        to="profiles.moderatorprofilemodel",
                        verbose_name="Moderator",
                    ),
                ),
            ],
            options={
                "verbose_name": "User profiles",
                "verbose_name_plural": "User profiles",
                "db_table": "profiles_users",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("moderator", "manager", "editor", "admin", "client"),
                        name="unique_of_profile_manager",
                        violation_error_code="unique_review",
                        violation_error_message="Combination of users profiles already exists.",
                    )
                ],
            },
        ),
    ]
