# Generated by Django 6.0.6 on 2026-07-04 01:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AdminProfileModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "language",
                    models.CharField(
                        choices=[("en", "English"), ("fr", "French"), ("ru", "Russia")],
                        default="ru",
                        max_length=10,
                    ),
                ),
                (
                    "time_zone",
                    models.CharField(default="Asia/Krasnoyarsk", max_length=50),
                ),
                (
                    "dashboard_preference",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="User preferences for dashboards and layout",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile_admin",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Admin profile",
                "verbose_name_plural": "Admin Profiles",
                "db_table": "profiles_admin",
            },
        ),
        migrations.CreateModel(
            name="ClientProfileModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "language",
                    models.CharField(
                        choices=[("en", "English"), ("fr", "French"), ("ru", "Russia")],
                        default="ru",
                        max_length=10,
                    ),
                ),
                (
                    "time_zone",
                    models.CharField(default="Asia/Krasnoyarsk", max_length=50),
                ),
                (
                    "dashboard_preference",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="User preferences for dashboards and layout",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile_client",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Client profile",
                "verbose_name_plural": "Client's profiles",
                "db_table": "profiles_Client",
            },
        ),
        migrations.CreateModel(
            name="ModeratorProfileModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "language",
                    models.CharField(
                        choices=[("en", "English"), ("fr", "French"), ("ru", "Russia")],
                        default="ru",
                        max_length=10,
                    ),
                ),
                (
                    "time_zone",
                    models.CharField(default="Asia/Krasnoyarsk", max_length=50),
                ),
                (
                    "dashboard_preference",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="User preferences for dashboards and layout",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile_moderator",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Moderator profile",
                "verbose_name_plural": "Moderator's profiles",
                "db_table": "profiles_moderator",
            },
        ),
        migrations.DeleteModel(
            name="ProfilesModels",
        ),
    ]
