# Generated by Django 6.0.6 on 2026-07-06 05:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0002_adminprofilemodel_clientprofilemodel_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="adminprofilemodel",
            options={
                "verbose_name": "Admin profile",
                "verbose_name_plural": "Admin profiles",
            },
        ),
        migrations.CreateModel(
            name="EditorProfileModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "language",
                    models.CharField(
                        choices=[("en", "English"), ("fr", "French"), ("ru", "Russia")],
                        default="ru",
                        max_length=10,
                    ),
                ),
                (
                    "time_zone",
                    models.CharField(default="Asia/Krasnoyarsk", max_length=50),
                ),
                (
                    "dashboard_preference",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="User preferences for dashboards and layout",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile_editor",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Editor profile",
                "verbose_name_plural": "Editor profiles",
                "db_table": "profiles_editor",
            },
        ),
        migrations.CreateModel(
            name="ManagerProfileModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "language",
                    models.CharField(
                        choices=[("en", "English"), ("fr", "French"), ("ru", "Russia")],
                        default="ru",
                        max_length=10,
                    ),
                ),
                (
                    "time_zone",
                    models.CharField(default="Asia/Krasnoyarsk", max_length=50),
                ),
                (
                    "dashboard_preference",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="User preferences for dashboards and layout",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile_manager",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Manager profile",
                "verbose_name_plural": "Manager profiles",
                "db_table": "profiles_manage",
            },
        ),
    ]
