# Generated by Django 6.0.6 on 2026-07-07 00:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "profiles",
            "0003_alter_adminprofilemodel_options_editorprofilemodel_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="adminprofilemodel",
            name="user",
        ),
        migrations.RemoveField(
            model_name="clientprofilemodel",
            name="user",
        ),
        migrations.RemoveField(
            model_name="editorprofilemodel",
            name="user",
        ),
        migrations.RemoveField(
            model_name="managerprofilemodel",
            name="user",
        ),
        migrations.RemoveField(
            model_name="moderatorprofilemodel",
            name="user",
        ),
    ]
