# Generated by Django 6.0.6 on 2026-07-07 01:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0004_remove_adminprofilemodel_user_and_more"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="clientprofilemodel",
            table="profiles_client",
        ),
    ]
