# Generated by Django 6.0.6 on 2026-07-07 01:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0005_alter_clientprofilemodel_table"),
        ("wagtailusers", "0015_userprofile_keyboard_shortcuts"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "userprofile_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailusers.userprofile",
                    ),
                ),
                (
                    "admin",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profiles_admin",
                        related_query_name="profile",
                        to="profiles.adminprofilemodel",
                        verbose_name="Admin",
                    ),
                ),
                (
                    "client",
                    models.ForeignKey(
                        blank=True,
                        db_comment="User profile",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profiles",
                        related_query_name="profiles_client",
                        to="profiles.clientprofilemodel",
                        verbose_name="Client",
                    ),
                ),
                (
                    "editor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profiles_editor",
                        related_query_name="profile",
                        to="profiles.editorprofilemodel",
                        verbose_name="Editor",
                    ),
                ),
                (
                    "manager",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile_manager",
                        related_query_name="profile",
                        to="profiles.managerprofilemodel",
                        verbose_name="Manager",
                    ),
                ),
                (
                    "moderator",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile_moderator",
                        related_query_name="profile_moderator",
                        to="profiles.moderatorprofilemodel",
                        verbose_name="Moderator",
                    ),
                ),
            ],
            options={
                "verbose_name": "User profiles",
                "verbose_name_plural": "User profiles",
                "db_table": "profiles_users",
            },
            bases=("wagtailusers.userprofile",),
        ),
    ]
