# Generated by Django 6.0.6 on 2026-07-10 02:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0003_remove_ordermodel_orders_profile_602e0e_idx_and_more"),
        ("profiles", "0007_userprofile_product"),
        ("wagtailusers", "0015_userprofile_keyboard_shortcuts"),
    ]

    operations = [
        migrations.AddField(
            model_name="adminprofilemodel",
            name="user",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="wagtailusers.userprofile",
                verbose_name="User",
            ),
        ),
        migrations.AddField(
            model_name="clientprofilemodel",
            name="user",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="wagtailusers.userprofile",
                verbose_name="User",
            ),
        ),
        migrations.AddField(
            model_name="editorprofilemodel",
            name="user",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="wagtailusers.userprofile",
                verbose_name="User",
            ),
        ),
        migrations.AddField(
            model_name="managerprofilemodel",
            name="user",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="wagtailusers.userprofile",
                verbose_name="User",
            ),
        ),
        migrations.AddField(
            model_name="moderatorprofilemodel",
            name="user",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="wagtailusers.userprofile",
                verbose_name="User",
            ),
        ),
        migrations.DeleteModel(
            name="UserProfile",
        ),
    ]
