# Generated by Django 6.0.6 on 2026-07-13 05:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0063_alter_productgalleryimagemodel_created_by_and_more"),
        ("profiles", "0009_userprofilemodel"),
        ("wagtailusers", "0015_userprofile_keyboard_shortcuts"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="UserProfileModel",
            new_name="UserProfileManagerModel",
        ),
        migrations.AlterField(
            model_name="adminprofilemodel",
            name="user",
            field=models.OneToOneField(
                db_comment="It is from the 'wagtail.users.models.UserProfile'",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="wagtailusers.userprofile",
                verbose_name="User",
            ),
        ),
        migrations.AlterField(
            model_name="clientprofilemodel",
            name="user",
            field=models.OneToOneField(
                db_comment="It is from the 'wagtail.users.models.UserProfile'",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="wagtailusers.userprofile",
                verbose_name="User",
            ),
        ),
        migrations.AlterField(
            model_name="editorprofilemodel",
            name="user",
            field=models.OneToOneField(
                db_comment="It is from the 'wagtail.users.models.UserProfile'",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="wagtailusers.userprofile",
                verbose_name="User",
            ),
        ),
        migrations.AlterField(
            model_name="managerprofilemodel",
            name="user",
            field=models.OneToOneField(
                db_comment="It is from the 'wagtail.users.models.UserProfile'",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="wagtailusers.userprofile",
                verbose_name="User",
            ),
        ),
        migrations.AlterField(
            model_name="moderatorprofilemodel",
            name="user",
            field=models.OneToOneField(
                db_comment="It is from the 'wagtail.users.models.UserProfile'",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="wagtailusers.userprofile",
                verbose_name="User",
            ),
        ),
        migrations.AddConstraint(
            model_name="userprofilemanagermodel",
            constraint=models.UniqueConstraint(
                fields=("moderator", "manager", "editor", "admin", "client"),
                name="unique_of_profile_manager",
                violation_error_code="unique_review",
                violation_error_message="Combination of users profiles already exists.",
            ),
        ),
    ]
