"""
Django settings for backend backend.

Generated by 'django-admin startproject' using Django 4.2.20.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/

project/settings_conf/settings_first.py:12
"""

import logging

from persons.apps import DEBUG
from project.settings_conf.settings_env import APP_TIME_ZONE

# Build paths inside the backend like this: BASE_DIR / 'subdir'.

# Quick-get_new_loop development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/
log = logging.getLogger(__name__)

# SECURITY WARNING: don't run with debug turned on in production!
# """" DEBUG """"


SECURE_SSL_REDIRECT = False
SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "http")
SECURE_BROWSER_XSS_FILTER = True
if DEBUG:
    SECURE_BROWSER_XSS_FILTER = False
    SECURE_CONTENT_TYPE_NOSNIFF = False
    SECURE_SSL_REDIRECT = False
    SESSION_COOKIE_SECURE = False
    CSRF_COOKIE_SECURE = False
    SECURE_CROSS_ORIGIN_OPENER_POLICY = None
    WHITENOISE_MAX_AGE = 0
    WHITENOISE_USE_FINDERS = False
SECURE_SSL_REDIRECT = False  # https is True & http is False

# ============================================
# APPLICATION DEFINITION
# ============================================
INSTALLED_APPS = [
    "daphne",
    "rest_framework",
    "drf_spectacular",
    "corsheaders",
    "drf_yasg",
    "adrf",
    "webpack_loader",
    "taggit",
    # Standard application
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django.contrib.sites",
    "django.contrib.humanize",
    # Allauth
    "allauth",
    "allauth.account",
    "allauth.socialaccount.providers.auth0",
    "allauth.socialaccount.providers.authentiq",
    "allauth.socialaccount.providers.google",
    "allauth.socialaccount.providers.mailru",
    "allauth.socialaccount.providers.telegram",
    "allauth.socialaccount.providers.vk",
    # Wagtail
    "wagtail.contrib.forms",
    "wagtail.contrib.redirects",
    "wagtail.embeds",
    "wagtail.sites",
    "wagtail.users",
    "wagtail.snippets",
    "wagtail.documents",
    "wagtail.images",
    "wagtail.search",
    "wagtail.locales",
    "wagtail.admin",
    "wagtail.contrib.settings",
    "wagtail",
    # My moduls
    "persons",
]


MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.locale.LocaleMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "wagtail.contrib.redirects.middleware.RedirectMiddleware",
    "allauth.account.middleware.AccountMiddleware",
]
from project.settings_conf.settings_db import *

# ============================================
# CLICKJACKING PROTECTION
# ============================================
X_FRAME_OPTIONS = "DENY"

# ============================================
# WHITEnOISE
# ============================================
# for a static files in production
# https://whitenoise.readthedocs.io/en/stable/django.html
WHITENOISE_MAX_AGE = 31536000  # static cache by 1 year
WHITENOISE_USE_FINDERS = True

# ============================================
# MAIN ROUTER PATH
# ============================================
ROOT_URLCONF = "project.urls"

# ============================================
# TEMPLATES
# ============================================
TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [
            os.path.join(BASE_DIR, "persons/templates"),
            os.path.join(BASE_DIR, "templates"),
        ],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

ASGI_APPLICATION = "project.asgi.application"

# ============================================
# CELERY
# ============================================
# 'celeryconfig.py' contains more information,
CELERY_TASK_TRACK_STARTED = True
CELERY_TASK_TIME_LIMIT = 30 * 60

# ============================================
# PASSWORD VALIDATION
# ============================================
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]

# ============================================
# HASH PASSWORDS
# ============================================
# https://docs.djangoproject.com/en/5.2/topics/auth/passwords/
PASSWORD_HASHERS = [
    "django.contrib.auth.hashers.PBKDF2PasswordHasher",
    "django.contrib.auth.hashers.PBKDF2SHA1PasswordHasher",
    "django.contrib.auth.hashers.Argon2PasswordHasher",
    "django.contrib.auth.hashers.BCryptSHA256PasswordHasher",
    "django.contrib.auth.hashers.BCryptPasswordHasher",
    "django.contrib.auth.hashers.ScryptPasswordHasher",
    "django.contrib.auth.hashers.MD5PasswordHasher",
]

PBKDF2_ITERATIONS = 720000

# ============================================
# LANGUAGE
# ============================================
# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = "en"
TIME_ZONE = f"{APP_TIME_ZONE.strip()}"

USE_I18N = True
WAGTAIL_I18N_ENABLED = True
# LANGUAGES - This sets which languages are available on the frontend of the site.
# WAGTAIL_CONTENT_LANGUAGES - This sets which the languages Wagtail content can be authored in.
LANGUAGE_CODE = "en"
WAGTAIL_CONTENT_LANGUAGES = LANGUAGES = [
    ("en", "English"),
    ("fr", "French"),
    ("ru", "Russia"),
]
USE_TZ = True

DATE_FORMAT = "d.m.Y"
DATETIME_FORMAT = "d.m.Y H:i"
DATETIME_FORMAT = "%Y-%m-%d %H:%M:%S.%f"
# Dates and numbers display in the user’s local format
USE_L10N = True

# ============================================
# STATIC FILES (CSS, JavaScript, Images)
# ============================================
# https://docs.djangoproject.com/en/4.2/howto/static-files/
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, "static"),
]
STATIC_ROOT = os.path.join(BASE_DIR, "collectstatic/")
STATIC_URL = "/static/"


MEDIA_URL = "/media/"
MEDIA_ROOT = os.path.join(BASE_DIR, "media")

# ============================================
# OPTIONS FOR FILE'S REPOSITORY/SOURCE
# ============================================
DEFAULT_FILE_STORAGE = "django.core.files.storage.FileSystemStorage"

# ============================================
# DEFAULT PRIMARY KEY FIELD TYPE
# ============================================
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"
DEFAULT_CHARSET = "utf-8"
AUTH_USER_MODEL = "persons.Users"
SITE_ID = 1

# ============================================
# LOGING AUTHENTICATION
# ============================================
LOGIN_URL = "/"
LOGIN_REDIRECT_URL = "wagtailadmin_home"
# LOGOUT_REDIRECT_URL = "/"

WAGTAILADMIN_BASE_URL = "/"

# ============================================
# DEBUG TOOLBAR - SERVER DAPHNE
# ============================================
DEBUG_TOOLBAR_CONFIG = {
    "SHOW_TOOLBAR_CALLBACK": lambda request: True,
}

# ============================================
# COOKIE
# ============================================
SESSION_COOKIE_HTTPONLY = False  # CSRF_COOKIE_HTTPONLY = True
SESSION_COOKIE_SECURE = False  # change to the True - CSRF_COOKIE_SECURE = True
SESSION_COOKIE_SAMESITE = "Lax"  # CSRF_COOKIE_SAMESITE = 'Lax'  # or 'Strict'
SESSION_COOKIE_AGE = 86400

# ============================================
# MODEL OF PAGE
# ============================================
DATA_UPLOAD_MAX_NUMBER_FIELDS = 10_000
DATA_UPLOAD_MAX_NUMBER_FILES = 10240
WAGTAIL_SITE_NAME = "Shop"

# ============================================
# APPLICATION DEFINITION
# ============================================
# file extension
f_extension = "csv, docx, pdf, rtf, txt, xlsx, zip"
WAGTAILDOCS_EXTENSIONS = list(f_extension.split(", "))
WAGTAILADMIN_LOGIN_FORM = "persons.forms.UsersLoginForm"
# WAGTAIL_APPEND_SLASH = "/"
