# Generated by Django 6.0.6 on 2026-06-18 01:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = []
