# Generated by Django 6.0.6 on 2026-07-17 10:29

from decimal import Decimal

import django.core.validators
import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("catalog", "0001_initial"),
        ("wagtailcore", "0097_baselogentry_uuid_action_timestamp_indexes"),
        ("wagtailimages", "0027_image_description"),
    ]

    operations = [
        migrations.CreateModel(
            name="BrandModel",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "name",
                    models.CharField(
                        help_text="The name of the category",
                        max_length=80,
                        unique=True,
                        validators=[
                            django.core.validators.MinLengthValidator(3),
                            django.core.validators.MaxLengthValidator(80),
                            django.core.validators.RegexValidator("^[\\w \\-_]{3,80}$"),
                        ],
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, max_length=250, null=True),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="The creation date"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="The last update date"
                    ),
                ),
            ],
            options={
                "verbose_name": "Brand",
                "db_table": "brand",
                "ordering": ("name",),
            },
        ),
        migrations.CreateModel(
            name="CatalogModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CategoryModel",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "name",
                    models.CharField(
                        help_text="The name of the category",
                        max_length=80,
                        unique=True,
                        validators=[
                            django.core.validators.MinLengthValidator(3),
                            django.core.validators.MaxLengthValidator(80),
                            django.core.validators.RegexValidator("^[\\w \\-_]{3,80}$"),
                        ],
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, max_length=250, null=True),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="The creation date"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="The last update date"
                    ),
                ),
            ],
            options={
                "verbose_name": "Category",
                "db_table": "category",
                "ordering": ("name",),
            },
        ),
        migrations.CreateModel(
            name="CategoryPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="The name of the category",
                        max_length=80,
                        unique=True,
                        validators=[
                            django.core.validators.MinLengthValidator(3),
                            django.core.validators.MaxLengthValidator(80),
                            django.core.validators.RegexValidator("^[\\w \\-_]{3,80}$"),
                        ],
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, max_length=250, null=True),
                ),
                ("created_at", models.DateField(help_text="The creation date")),
                ("updated_at", models.DateField(help_text="The last update date")),
            ],
            options={
                "abstract": False,
            },
            bases=("wagtailcore.page",),
        ),
        migrations.CreateModel(
            name="ProductCharacteristics",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "description",
                    models.TextField(blank=True, max_length=250, null=True),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="The creation date"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="The last update date"
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        db_index=True,
                        help_text="The name of the property",
                        max_length=80,
                        validators=[
                            django.core.validators.MinLengthValidator(3),
                            django.core.validators.MaxLengthValidator(80),
                            django.core.validators.RegexValidator("^[\\w \\-_]{3,80}$"),
                        ],
                    ),
                ),
                (
                    "value",
                    models.CharField(
                        default="-",
                        help_text="The value of the property",
                        max_length=10,
                        validators=[django.core.validators.MaxLengthValidator(10)],
                    ),
                ),
            ],
            options={
                "verbose_name": "Product Characteristic",
                "verbose_name_plural": "Product Characteristics",
                "db_table": "product_characteristics",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="ProductGalleryImageModel",
            fields=[
                (
                    "sort_order",
                    models.IntegerField(blank=True, editable=False, null=True),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="The creation date"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="The last update date"
                    ),
                ),
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "caption",
                    wagtail.fields.RichTextField(
                        blank=True,
                        help_text="Comment to the product",
                        max_length=80,
                        null=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                regex="^[\\.>< =\\\"\\'\\/ \\w \\\"'_%+-]+$"
                            )
                        ],
                    ),
                ),
                (
                    "version",
                    models.IntegerField(
                        default=0,
                        help_text="The version of changing the product",
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(9999),
                        ],
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether this item is active.",
                    ),
                ),
                (
                    "published_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Designates when this item was published",
                        null=True,
                    ),
                ),
            ],
            options={
                "verbose_name": "Catalog",
                "verbose_name_plural": "Catalog",
                "db_table": "product_gallery",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ProductGalleryImagePage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sort_order",
                    models.IntegerField(blank=True, editable=False, null=True),
                ),
                ("caption", models.CharField(blank=True, max_length=250)),
            ],
            options={
                "ordering": ["sort_order"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ProductModel",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="The creation date"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="The last update date"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether this item is used or not",
                    ),
                ),
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "name",
                    models.CharField(
                        help_text="The name of the product",
                        max_length=80,
                        unique=True,
                        validators=[
                            django.core.validators.MinLengthValidator(3),
                            django.core.validators.MaxLengthValidator(80),
                            django.core.validators.RegexValidator(
                                message="Only letters, numbers, spaces             and underscores are allowed.",
                                regex="(^[A-ZА-ЯЁ0-9][\\w\\dА-ЯЁа-яё\\s]+$)",
                            ),
                        ],
                        verbose_name="Product Name",
                    ),
                ),
                (
                    "product_sku",
                    models.CharField(
                        db_index=True,
                        help_text="The required unique SKU/code/name of the product",
                        max_length=100,
                        unique=True,
                        validators=[
                            django.core.validators.MinLengthValidator(3),
                            django.core.validators.MaxLengthValidator(100),
                            django.core.validators.RegexValidator(
                                message="Only letters, numbers and underscores are allowed.",
                                regex="^[a-zA-Z0-9_\\-]+$",
                            ),
                        ],
                        verbose_name="Product SKU",
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="The price of the product",
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00")),
                            django.core.validators.DecimalValidator(
                                decimal_places=2, max_digits=10
                            ),
                        ],
                        verbose_name="Product Price on the order moment",
                    ),
                ),
                (
                    "product_discount",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                        verbose_name="Product Discount on the order moment",
                    ),
                ),
                (
                    "describe_preview",
                    wagtail.fields.RichTextField(
                        blank=True,
                        help_text="The preview description of the product",
                        null=True,
                        validators=[django.core.validators.MaxLengthValidator(150)],
                    ),
                ),
                (
                    "description",
                    wagtail.fields.RichTextField(
                        blank=True,
                        help_text="The description of the product",
                        null=True,
                        validators=[django.core.validators.MaxLengthValidator(1000)],
                    ),
                ),
                (
                    "discount_percent",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="The discount percentage of the product",
                        max_digits=4,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00")),
                            django.core.validators.MaxValueValidator(Decimal("99.99")),
                            django.core.validators.DecimalValidator(
                                decimal_places=2, max_digits=4
                            ),
                        ],
                    ),
                ),
                (
                    "stock_quantity",
                    models.PositiveIntegerField(
                        db_index=True,
                        default=0,
                        help_text="The quantity of the product",
                    ),
                ),
                (
                    "attributes_additional",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Uniquer (for product) characteristics of the one product.",
                        null=True,
                    ),
                ),
            ],
            options={
                "verbose_name": "Product",
                "db_table": "product_model",
            },
        ),
        migrations.CreateModel(
            name="ProductPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                ("name", models.CharField(max_length=80)),
                (
                    "description",
                    models.TextField(blank=True, max_length=250, null=True),
                ),
                ("created_at", models.DateField(help_text="The creation date")),
                ("updated_at", models.DateField(help_text="The last update date")),
            ],
            options={
                "abstract": False,
            },
            bases=("wagtailcore.page",),
        ),
        migrations.CreateModel(
            name="ProductPageModel",
            fields=[
                (
                    "name",
                    models.CharField(
                        help_text="The name of the category",
                        max_length=80,
                        unique=True,
                        validators=[
                            django.core.validators.MinLengthValidator(3),
                            django.core.validators.MaxLengthValidator(80),
                            django.core.validators.RegexValidator("^[\\w \\-_]{3,80}$"),
                        ],
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, max_length=250, null=True),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="The creation date"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="The last update date"
                    ),
                ),
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "is_active",
                    models.BooleanField(default=False, verbose_name="Is active?"),
                ),
            ],
            options={
                "verbose_name": "Product Page",
                "db_table": "product_page_model",
            },
        ),
        migrations.CreateModel(
            name="OneImageModels",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="The title of the schematic. Available char: 'A-Za-z0-9\\. \\\"'_%+-'",
                        max_length=100,
                        unique=True,
                        validators=[
                            django.core.validators.MaxLengthValidator(100),
                            django.core.validators.MinLengthValidator(3),
                            django.core.validators.RegexValidator(
                                regex="^[A-Za-zА-ЯЪа-яъ0-9\\. \\\"'_%+-]+$"
                            ),
                        ],
                        verbose_name="Title",
                    ),
                ),
                (
                    "describe",
                    models.TextField(
                        blank=True,
                        help_text="The short description of the image/ Available char: 'A-Za-z0-9\\. \\\"'_%+-'",
                        max_length=80,
                        null=True,
                        validators=[
                            django.core.validators.MaxLengthValidator(80),
                            django.core.validators.RegexValidator(
                                regex="^[A-Za-z0-9\\. \\\"'_%+-]*$"
                            ),
                        ],
                    ),
                ),
                (
                    "label",
                    models.CharField(
                        default="label",
                        max_length=25,
                        validators=[
                            django.core.validators.MinLengthValidator(5),
                            django.core.validators.MaxLengthValidator(25),
                            django.core.validators.RegexValidator(
                                regex="^[A-Za-z0-9\\. \\\"'_%+-]+$"
                            ),
                        ],
                    ),
                ),
                (
                    "x",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=5,
                        validators=[
                            django.core.validators.MaxValueValidator(100.0),
                            django.core.validators.MinValueValidator(0.0),
                        ],
                        verbose_name="x ->",
                    ),
                ),
                (
                    "y",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=5,
                        validators=[
                            django.core.validators.MaxValueValidator(100.0),
                            django.core.validators.MinValueValidator(0.0),
                        ],
                        verbose_name="y ↑",
                    ),
                ),
                (
                    "image",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        related_query_name="image_%(app_label)s_%(class)s_related",
                        to="wagtailimages.image",
                    ),
                ),
            ],
            options={
                "verbose_name": "Image",
                "verbose_name_plural": "Images",
                "db_table": "images",
                "ordering": ["-image"],
            },
        ),
    ]
