# Generated by Django 6.0.6 on 2026-06-18 02:58

from decimal import Decimal

import django.core.validators
import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0002_auto_20260618_0832"),
        ("wagtailimages", "0027_image_description"),
    ]

    operations = [
        migrations.CreateModel(
            name="BrandModel",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "name",
                    models.CharField(
                        help_text="The name of the category",
                        max_length=80,
                        unique=True,
                        validators=[
                            django.core.validators.MinLengthValidator(3),
                            django.core.validators.MaxLengthValidator(80),
                            django.core.validators.RegexValidator("^[\\w \\-_]{3,80}$"),
                        ],
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="The creation date"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="The last update date"
                    ),
                ),
            ],
            options={
                "verbose_name": "Brand",
                "db_table": "brand",
                "ordering": ("-name",),
            },
        ),
        migrations.CreateModel(
            name="CategoryModel",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "name",
                    models.CharField(
                        help_text="The name of the category",
                        max_length=80,
                        unique=True,
                        validators=[
                            django.core.validators.MinLengthValidator(3),
                            django.core.validators.MaxLengthValidator(80),
                            django.core.validators.RegexValidator("^[\\w \\-_]{3,80}$"),
                        ],
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="The creation date"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="The last update date"
                    ),
                ),
            ],
            options={
                "verbose_name": "Category",
                "db_table": "category",
                "ordering": ("-name",),
            },
        ),
        migrations.CreateModel(
            name="ProductPageModel",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name="ProductModel",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="The creation date"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="The last update date"
                    ),
                ),
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "name",
                    models.CharField(
                        help_text="The name of the product",
                        max_length=80,
                        unique=True,
                        validators=[
                            django.core.validators.MinLengthValidator(3),
                            django.core.validators.MaxLengthValidator(80),
                            django.core.validators.RegexValidator(
                                "[\\w., \\-_]{3:100}"
                            ),
                        ],
                    ),
                ),
                (
                    "describe_preview",
                    wagtail.fields.RichTextField(
                        blank=True,
                        help_text="The preview description of the product",
                        null=True,
                        validators=[
                            django.core.validators.MaxLengthValidator(150),
                            django.core.validators.RegexValidator(
                                "[\\w., \\-_]{0:150}"
                            ),
                        ],
                    ),
                ),
                (
                    "description",
                    wagtail.fields.RichTextField(
                        blank=True,
                        help_text="The description of the product",
                        null=True,
                        validators=[
                            django.core.validators.MaxLengthValidator(1000),
                            django.core.validators.RegexValidator(
                                "[\\w., \\-_]{0:150}"
                            ),
                        ],
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="The price of the product",
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00")),
                            django.core.validators.MaxValueValidator(
                                Decimal("99999999.99")
                            ),
                            django.core.validators.DecimalValidator(
                                decimal_places=2, max_digits=10
                            ),
                        ],
                    ),
                ),
                (
                    "discount_percent",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="The discount percentage of the product",
                        max_digits=4,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00")),
                            django.core.validators.MaxValueValidator(Decimal("99.99")),
                            django.core.validators.DecimalValidator(
                                decimal_places=2, max_digits=4
                            ),
                        ],
                    ),
                ),
                (
                    "stock_quantity",
                    models.IntegerField(
                        default=0, help_text="The quantity of the product"
                    ),
                ),
                (
                    "brand",
                    models.ForeignKey(
                        help_text="The brand of the product",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="catalog.brandmodel",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        help_text="The category of the product",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="catalog.categorymodel",
                    ),
                ),
            ],
            options={
                "ordering": ["-updated_at"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ProductGalleryImageModel",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "caption",
                    models.CharField(
                        blank=True,
                        help_text="The caption of the image",
                        max_length=250,
                        null=True,
                    ),
                ),
                (
                    "image",
                    models.ForeignKey(
                        help_text="The image",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="wagtailimages.image",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="catalog.productmodel",
                    ),
                ),
                (
                    "page",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gallery_images",
                        to="catalog.productpagemodel",
                    ),
                ),
            ],
        ),
    ]
