# Generated by Django 6.0.6 on 2026-07-17 10:29

import django.db.models.deletion
import modelcluster.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("catalog", "0002_initial"),
        ("profiles", "0002_initial"),
        ("wagtailimages", "0027_image_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="productgalleryimagemodel",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                db_comment="This is a user's profile created position. Just that is goes not to the direct user. That is go to\n        the profile user: 'UserProfileManagerModel' =>         'profiles.models.model_<client | admin | editor | manager | client| moderator >' =>         'wagtail.users.models.UserProfile' => 'persons.models.Users' model.\n        If need  a direct user mean we get of user through the 'ProfilesModel' model..\n        ",
                help_text="THe user who created the position",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(app_label)s_%(class)s_product_characteristics_created",
                to="profiles.userprofilemanagermodel",
            ),
        ),
        migrations.AddField(
            model_name="productgalleryimagemodel",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                db_comment="This is a user last updated position.\n        If need a direct user mean we act by analogy the 'self.created_by ",
                help_text="The user who last updated the position",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(app_label)s_%(class)s_product_characteristics_updated",
                to="profiles.userprofilemanagermodel",
            ),
        ),
        migrations.AddField(
            model_name="productgalleryimagepage",
            name="image",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="wagtailimages.image",
            ),
        ),
        migrations.AddField(
            model_name="productmodel",
            name="brand",
            field=models.ForeignKey(
                help_text="The brand of the product",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="catalog.brandmodel",
            ),
        ),
        migrations.AddField(
            model_name="productmodel",
            name="category",
            field=models.ForeignKey(
                help_text="The category of the product",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="catalog.categorymodel",
            ),
        ),
        migrations.AddField(
            model_name="productmodel",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                db_comment="This is a user's profile created position. Just that is goes not to the direct user. That is go to\n        the profile user: 'UserProfileManagerModel' =>         'profiles.models.model_<client | admin | editor | manager | client| moderator >' =>         'wagtail.users.models.UserProfile' => 'persons.models.Users' model.\n        If need  a direct user mean we get of user through the 'ProfilesModel' model..\n        ",
                help_text="THe user who created the position",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(app_label)s_%(class)s_product_characteristics_created",
                to="profiles.userprofilemanagermodel",
            ),
        ),
        migrations.AddField(
            model_name="productmodel",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                db_comment="This is a user last updated position.\n        If need a direct user mean we act by analogy the 'self.created_by ",
                help_text="The user who last updated the position",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(app_label)s_%(class)s_product_characteristics_updated",
                to="profiles.userprofilemanagermodel",
            ),
        ),
        migrations.AddField(
            model_name="productgalleryimagepage",
            name="product",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="catalog.productmodel",
            ),
        ),
        migrations.AddField(
            model_name="productgalleryimagemodel",
            name="product",
            field=models.ForeignKey(
                limit_choices_to={"is_active": True},
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                related_query_name="product_related",
                to="catalog.productmodel",
            ),
        ),
        migrations.AddField(
            model_name="productcharacteristics",
            name="product",
            field=modelcluster.fields.ParentalKey(
                blank=True,
                help_text="Commons characteristics of the ont product.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="characteristics",
                to="catalog.productmodel",
                verbose_name="product Characteristics",
            ),
        ),
        migrations.AddField(
            model_name="oneimagemodels",
            name="product",
            field=modelcluster.fields.ParentalKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="images",
                related_query_name="product_%(app_label)s_%(class)s_related",
                to="catalog.productmodel",
            ),
        ),
        migrations.AddField(
            model_name="productgalleryimagepage",
            name="page",
            field=modelcluster.fields.ParentalKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="gallery_images",
                to="catalog.productpage",
            ),
        ),
        migrations.AddField(
            model_name="productgalleryimagemodel",
            name="page",
            field=models.ForeignKey(
                limit_choices_to={"is_active": True},
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="catalog.productpagemodel",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="productmodel",
            unique_together={("name", "brand"), ("name", "category")},
        ),
        migrations.AlterUniqueTogether(
            name="productcharacteristics",
            unique_together={("name", "value")},
        ),
        migrations.AlterUniqueTogether(
            name="productgalleryimagemodel",
            unique_together={("page", "product")},
        ),
    ]
