# Generated by Django 6.0.6 on 2026-06-18 04:30
from datetime import datetime

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models

from project.settings_conf.settings_first import DATETIME_FORMAT


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0003_brandmodel_categorymodel_productpagemodel_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductCharacteristics",
            fields=[
                (
                    "description",
                    models.TextField(blank=True, max_length=250, null=True),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="The creation date"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="The last update date"
                    ),
                ),
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "name",
                    models.CharField(
                        db_index=True,
                        help_text="The name of the category",
                        max_length=80,
                        unique=True,
                        validators=[
                            django.core.validators.MinLengthValidator(3),
                            django.core.validators.MaxLengthValidator(80),
                            django.core.validators.RegexValidator("^[\\w \\-_]{3,80}$"),
                        ],
                    ),
                ),
                (
                    "value",
                    models.CharField(
                        default="-",
                        max_length=10,
                        validators=[django.core.validators.MaxLengthValidator(10)],
                    ),
                ),
            ],
            options={
                "verbose_name": "Product Characteristic",
                "verbose_name_plural": "Product Characteristics",
                "db_table": "product_characteristics",
                "ordering": ["name"],
            },
        ),
        migrations.AlterModelOptions(
            name="brandmodel",
            options={"verbose_name": "Brand"},
        ),
        migrations.AlterModelOptions(
            name="categorymodel",
            options={"verbose_name": "Category"},
        ),
        migrations.AlterModelOptions(
            name="productgalleryimagemodel",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Product Gallery Image",
                "verbose_name_plural": "Product Gallery Images",
            },
        ),
        migrations.AlterModelOptions(
            name="productmodel",
            options={"verbose_name": "Product"},
        ),
        migrations.AlterModelOptions(
            name="productpagemodel",
            options={"verbose_name": "Product Page"},
        ),
        migrations.AddField(
            model_name="brandmodel",
            name="description",
            field=models.TextField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name="categorymodel",
            name="description",
            field=models.TextField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name="productgalleryimagemodel",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                default=datetime.now().strftime(DATETIME_FORMAT),
                help_text="The creation date",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="productgalleryimagemodel",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, help_text="The last update date"),
        ),
        migrations.AddField(
            model_name="productmodel",
            name="attributes_additional",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Uniquer (for product) characteristics of the one product.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="productmodel",
            name="name",
            field=models.CharField(
                db_index=True,
                help_text="The name of the product",
                max_length=80,
                unique=True,
                validators=[
                    django.core.validators.MinLengthValidator(3),
                    django.core.validators.MaxLengthValidator(80),
                    django.core.validators.RegexValidator("[\\w., \\-_]{3:100}"),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="productmodel",
            name="stock_quantity",
            field=models.IntegerField(
                db_index=True, default=0, help_text="The quantity of the product"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="productgalleryimagemodel",
            unique_together={("page", "product")},
        ),
        migrations.AlterUniqueTogether(
            name="productmodel",
            unique_together={("name", "category")},
        ),
        migrations.AlterModelTable(
            name="productgalleryimagemodel",
            table="product_gallery_image",
        ),
        migrations.AlterModelTable(
            name="productmodel",
            table="product_model",
        ),
        migrations.AlterModelTable(
            name="productpagemodel",
            table="product_page_model",
        ),
        migrations.AddField(
            model_name="productmodel",
            name="attributes",
            field=models.ForeignKey(
                blank=True,
                help_text="Commons characteristics of the ont product.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="catalog.productcharacteristics",
                verbose_name="+",
            ),
        ),
    ]
