# Generated by Django 6.0.6 on 2026-06-18 05:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0009_emailaddress_unique_primary_email"),
        ("catalog", "0004_productcharacteristics_alter_brandmodel_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="productgalleryimagemodel",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                help_text="THe user who created the position",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(app_label)s_%(class)s_product_characteristics_created",
                to="account.emailaddress",
            ),
        ),
        migrations.AddField(
            model_name="productgalleryimagemodel",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                help_text="The user who last updated the position",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(app_label)s_%(class)s_product_characteristics_updated",
                to="account.emailaddress",
            ),
        ),
        migrations.AddField(
            model_name="productmodel",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                help_text="THe user who created the position",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(app_label)s_%(class)s_product_characteristics_created",
                to="account.emailaddress",
            ),
        ),
        migrations.AddField(
            model_name="productmodel",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                help_text="The user who last updated the position",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(app_label)s_%(class)s_product_characteristics_updated",
                to="account.emailaddress",
            ),
        ),
    ]
