# Generated by Django 6.0.6 on 2026-06-18 05:23
from datetime import datetime

import django.core.validators
from django.db import migrations, models

from project.settings_conf.settings_first import DATETIME_FORMAT


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0005_productgalleryimagemodel_created_by_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="productpagemodel",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                default=datetime.now().strftime(DATETIME_FORMAT),
                help_text="The creation date",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="productpagemodel",
            name="description",
            field=models.TextField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name="productpagemodel",
            name="name",
            field=models.CharField(
                default="0:0:0 0:0:0.0",
                help_text="The name of the category",
                max_length=80,
                unique=True,
                validators=[
                    django.core.validators.MinLengthValidator(3),
                    django.core.validators.MaxLengthValidator(80),
                    django.core.validators.RegexValidator("^[\\w \\-_]{3,80}$"),
                ],
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="productpagemodel",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, help_text="The last update date"),
        ),
    ]
