# Generated by Django 6.0.6 on 2026-06-18 05:50

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0006_productpagemodel_created_at_and_more"),
        ("wagtailcore", "0097_baselogentry_uuid_action_timestamp_indexes"),
    ]

    operations = [
        migrations.CreateModel(
            name="CategoryPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="The name of the category",
                        max_length=80,
                        unique=True,
                        validators=[
                            django.core.validators.MinLengthValidator(3),
                            django.core.validators.MaxLengthValidator(80),
                            django.core.validators.RegexValidator("^[\\w \\-_]{3,80}$"),
                        ],
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, max_length=250, null=True),
                ),
                ("created_at", models.DateField(help_text="The creation date")),
                ("updated_at", models.DateField(help_text="The last update date")),
            ],
            options={
                "abstract": False,
            },
            bases=("wagtailcore.page",),
        ),
    ]
