# Generated by Django 6.0.6 on 2026-06-19 10:27

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0008_productpage_alter_productmodel_describe_preview_and_more"),
        ("wagtailimages", "0027_image_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="productgalleryimagemodel",
            name="is_active",
            field=models.BooleanField(
                default=False, help_text="Designates whether this item is active."
            ),
        ),
        migrations.AddField(
            model_name="productgalleryimagemodel",
            name="published_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Designates when this item was published",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="productgalleryimagemodel",
            name="version",
            field=models.IntegerField(
                default=0,
                help_text="The version of changing the product",
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(9999),
                ],
            ),
        ),
        migrations.AddField(
            model_name="productmodel",
            name="is_active",
            field=models.BooleanField(
                default=False, help_text="Designates whether this item is used or not"
            ),
        ),
        migrations.AlterField(
            model_name="productgalleryimagemodel",
            name="image",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="wagtailimages.image",
            ),
        ),
        migrations.AlterField(
            model_name="productgalleryimagemodel",
            name="page",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="catalog.productpagemodel",
            ),
        ),
    ]
