# Generated by Django 6.0.6 on 2026-06-19 09:19

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0009_productgalleryimagemodel_is_active_and_more"),
        ("wagtailimages", "0027_image_description"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="productgalleryimagemodel",
            name="image",
        ),
        migrations.AlterField(
            model_name="productgalleryimagemodel",
            name="page",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="catalog.productpagemodel",
            ),
        ),
        migrations.AlterField(
            model_name="productgalleryimagemodel",
            name="version",
            field=models.IntegerField(
                default=0,
                help_text="The version of changing the product",
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(9999),
                ],
            ),
        ),
        migrations.AddField(
            model_name="productgalleryimagemodel",
            name="image",
            field=models.ManyToManyField(related_name="+", to="wagtailimages.image"),
        ),
    ]
