# Generated by Django 6.0.6 on 2026-06-19 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0009_productgalleryimagemodel_is_active_and_more"),
    ]

    operations = []
