# Generated by Django 6.0.6 on 2026-06-20 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0010_auto_20260619_1729"),
        ("wagtailimages", "0027_image_description"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="productgalleryimagemodel",
            name="image",
        ),
        migrations.AddField(
            model_name="productgalleryimagemodel",
            name="image",
            field=models.ManyToManyField(
                related_name="+",
                related_query_name="image_query_related",
                to="wagtailimages.image",
            ),
        ),
    ]
