# Generated by Django 6.0.6 on 2026-06-20 03:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0011_remove_productgalleryimagemodel_image_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="productpagemodel",
            name="is_active",
            field=models.BooleanField(default=False, verbose_name="Is active?"),
        ),
        migrations.AlterField(
            model_name="productgalleryimagemodel",
            name="product",
            field=models.ForeignKey(
                limit_choices_to={"is_active": True},
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                related_query_name="product_related",
                to="catalog.productmodel",
            ),
        ),
    ]
