# Generated by Django 6.0.6 on 2026-06-20 03:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0012_productpagemodel_is_active_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productgalleryimagemodel",
            name="page",
            field=models.ForeignKey(
                limit_choices_to={"is_active": True},
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="catalog.productpagemodel",
            ),
        ),
    ]
