# Generated by Django 6.0.6 on 2026-06-20 06:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0013_alter_productgalleryimagemodel_page"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productcharacteristics",
            name="name",
            field=models.CharField(
                db_index=True,
                help_text="The name of the category",
                max_length=80,
                validators=[
                    django.core.validators.MinLengthValidator(3),
                    django.core.validators.MaxLengthValidator(80),
                    django.core.validators.RegexValidator("^[\\w \\-_]{3,80}$"),
                ],
            ),
        ),
        migrations.AlterUniqueTogether(
            name="productcharacteristics",
            unique_together={("name", "value")},
        ),
    ]
