# Generated by Django 6.0.6 on 2026-06-20 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0014_alter_productcharacteristics_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="productgalleryimagemodel",
            name="product_characteristic",
            field=models.ManyToManyField(
                related_name="+",
                related_query_name="product_characteristics_related",
                to="catalog.productcharacteristics",
            ),
        ),
    ]
