# Generated by Django 6.0.6 on 2026-06-21 01:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0015_productgalleryimagemodel_product_characteristic"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="productgalleryimagemodel",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Catalog",
                "verbose_name_plural": "Catalog",
            },
        ),
    ]
