# Generated by Django 6.0.6 on 2026-06-21 04:56

import django.core.validators
import django.db.models.deletion
import modelcluster.fields
import modelsearch.index
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0016_alter_productgalleryimagemodel_options"),
        ("wagtailcore", "0097_baselogentry_uuid_action_timestamp_indexes"),
        ("wagtailimages", "0027_image_description"),
    ]

    operations = [
        migrations.CreateModel(
            name="SchematicModel",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "description",
                    models.TextField(blank=True, max_length=250, null=True),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="The creation date"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="The last update date"
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="The title of the schematic",
                        max_length=255,
                        verbose_name="Title",
                    ),
                ),
                (
                    "image",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        related_query_name="image_%(app_label)s_%(class)s_related",
                        to="wagtailimages.image",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=(modelsearch.index.Indexed, models.Model),
        ),
        migrations.CreateModel(
            name="ProductPageTest",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                (
                    "schematic",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="product_page_schematic",
                        to="catalog.schematicmodel",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("wagtailcore.page",),
        ),
        migrations.CreateModel(
            name="SchematicPoint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sort_order",
                    models.IntegerField(blank=True, editable=False, null=True),
                ),
                ("label", models.CharField(max_length=254, verbose_name="label")),
                (
                    "x",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=5,
                        validators=[
                            django.core.validators.MaxValueValidator(100.0),
                            django.core.validators.MinValueValidator(0.0),
                        ],
                        verbose_name="X ->",
                    ),
                ),
                (
                    "y",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=5,
                        validators=[
                            django.core.validators.MaxValueValidator(100.0),
                            django.core.validators.MinValueValidator(0.0),
                        ],
                        verbose_name="Y ↑",
                    ),
                ),
                (
                    "schematics",
                    modelcluster.fields.ParentalKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="points",
                        to="catalog.schematicmodel",
                    ),
                ),
            ],
            options={
                "verbose_name": "Point",
                "verbose_name_plural": "Points",
            },
        ),
    ]
