# Generated by Django 6.0.6 on 2026-06-21 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0017_schematicmodel_productpagetest_schematicpoint"),
        ("wagtailcore", "0097_baselogentry_uuid_action_timestamp_indexes"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="ProductPageTest",
            new_name="ProductPageTestMy",
        ),
        migrations.AlterModelOptions(
            name="schematicmodel",
            options={"verbose_name": "Schematic", "verbose_name_plural": "Schematics"},
        ),
    ]
