# Generated by Django 6.0.6 on 2026-06-22 04:46
from datetime import datetime

import django.core.validators
import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0018_rename_productpagetest_productpagetestmy_and_more"),
        ("wagtailimages", "0027_image_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productgalleryimagemodel",
            name="caption",
            field=wagtail.fields.RichTextField(
                blank=True,
                help_text="Comment to the product",
                max_length=250,
                null=True,
            ),
        ),
        migrations.RemoveField(
            model_name="productgalleryimagemodel",
            name="image",
        ),
        migrations.AlterField(
            model_name="productgalleryimagemodel",
            name="product_characteristic",
            field=models.ManyToManyField(
                related_name="characteristic",
                related_query_name="product_characteristics_related",
                to="catalog.productcharacteristics",
            ),
        ),
        migrations.CreateModel(
            name="OneImageModels",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="The title of the schematic. Available char: 'A-Za-z0-9\\. \\\"'_%+-'",
                        max_length=100,
                        unique=True,
                        validators=[
                            django.core.validators.MaxLengthValidator(100),
                            django.core.validators.MinLengthValidator(3),
                            django.core.validators.RegexValidator(
                                regex="^[A-Za-z0-9\\. \\\"'_%+-]+$"
                            ),
                        ],
                        verbose_name="Title",
                    ),
                ),
                (
                    "descride",
                    models.TextField(
                        blank=True,
                        help_text="The short description of the image/ Available char: 'A-Za-z0-9\\. \\\"'_%+-'",
                        max_length=80,
                        null=True,
                        validators=[
                            django.core.validators.MaxLengthValidator(80),
                            django.core.validators.RegexValidator(
                                regex="^[A-Za-z0-9\\. \\\"'_%+-]*$"
                            ),
                        ],
                    ),
                ),
                (
                    "label",
                    models.CharField(
                        default="label",
                        max_length=25,
                        validators=[
                            django.core.validators.MinLengthValidator(5),
                            django.core.validators.MaxLengthValidator(25),
                            django.core.validators.RegexValidator(
                                regex="^[A-Za-z0-9\\. \\\"'_%+-]+$"
                            ),
                        ],
                    ),
                ),
                (
                    "x",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=5,
                        validators=[
                            django.core.validators.MaxValueValidator(100.0),
                            django.core.validators.MinValueValidator(0.0),
                        ],
                        verbose_name="x ->",
                    ),
                ),
                (
                    "y",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=5,
                        validators=[
                            django.core.validators.MaxValueValidator(100.0),
                            django.core.validators.MinValueValidator(0.0),
                        ],
                        verbose_name="y ↑",
                    ),
                ),
                (
                    "image",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        related_query_name="image_%(app_label)s_%(class)s_related",
                        to="wagtailimages.image",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="productgalleryimagemodel",
            name="image",
            field=models.ForeignKey(
                null=True,
                blank=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="images_related",
                related_query_name="image_query_related",
                to="catalog.oneimagemodels",
            ),
            preserve_default=False,
        ),
    ]
