# Generated by Django 6.0.6 on 2026-06-22 05:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0019_alter_productgalleryimagemodel_caption_and_more"),
        ("wagtailimages", "0027_image_description"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="schematicmodel",
            name="image",
        ),
        migrations.RemoveField(
            model_name="schematicpoint",
            name="schematics",
        ),
        migrations.RenameField(
            model_name="oneimagemodels",
            old_name="descride",
            new_name="describe",
        ),
        migrations.AlterField(
            model_name="oneimagemodels",
            name="image",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                related_query_name="image_%(app_label)s_%(class)s_related",
                to="wagtailimages.image",
            ),
        ),
        migrations.AlterField(
            model_name="productgalleryimagemodel",
            name="image",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="images",
                related_query_name="image_query_related",
                to="catalog.oneimagemodels",
            ),
        ),
        migrations.DeleteModel(
            name="ProductPageTestMy",
        ),
        migrations.DeleteModel(
            name="SchematicModel",
        ),
        migrations.DeleteModel(
            name="SchematicPoint",
        ),
    ]
