# Generated by Django 6.0.6 on 2026-06-22 05:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0020_remove_schematicmodel_image_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="productgalleryimagemodel",
            name="image",
        ),
        migrations.AddField(
            model_name="oneimagemodels",
            name="image_show",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="images",
                related_query_name="image_query_related",
                to="catalog.productgalleryimagemodel",
            ),
        ),
    ]
