# Generated by Django 6.0.6 on 2026-06-22 05:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0021_remove_productgalleryimagemodel_image_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productgalleryimagemodel",
            name="caption",
            field=models.TextField(
                blank=True,
                help_text="Comment to the product",
                max_length=80,
                null=True,
                validators=[
                    django.core.validators.MaxLengthValidator(80),
                    django.core.validators.RegexValidator(
                        regex="^[A-Za-z0-9\\. \\\"'_%+-]*$"
                    ),
                ],
            ),
        ),
    ]
