# Generated by Django 6.0.6 on 2026-06-22 05:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0022_alter_productgalleryimagemodel_caption"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="oneimagemodels",
            name="image_show",
        ),
        migrations.AddField(
            model_name="productgalleryimagemodel",
            name="image",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="images",
                related_query_name="image_query_related",
                to="catalog.oneimagemodels",
            ),
        ),
        migrations.RemoveField(
            model_name="productgalleryimagemodel",
            name="product_characteristic",
        ),
        migrations.AddField(
            model_name="productgalleryimagemodel",
            name="product_characteristic",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="characteristic",
                related_query_name="product_characteristics_related",
                to="catalog.productcharacteristics",
            ),
        ),
    ]
