# Generated by Django 6.0.6 on 2026-06-22 06:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0023_remove_oneimagemodels_image_show_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productgalleryimagemodel",
            name="image",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="images",
                to="catalog.oneimagemodels",
            ),
        ),
    ]
