# Generated by Django 6.0.6 on 2026-06-22 06:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0024_alter_productgalleryimagemodel_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="productgalleryimagemodel",
            name="image",
        ),
        migrations.AddField(
            model_name="oneimagemodels",
            name="product",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="images",
                to="catalog.productgalleryimagemodel",
            ),
        ),
    ]
