# Generated by Django 6.0.6 on 2026-06-22 08:26

import django.db.models.deletion
import modelcluster.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0025_remove_productgalleryimagemodel_image_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="oneimagemodels",
            name="product",
            field=modelcluster.fields.ParentalKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="images",
                to="catalog.productgalleryimagemodel",
            ),
        ),
    ]
