# Generated by Django 6.0.6 on 2026-06-22 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0026_alter_oneimagemodels_product"),
    ]

    operations = [
        migrations.AddField(
            model_name="productgalleryimagemodel",
            name="sort_order",
            field=models.IntegerField(blank=True, editable=False, null=True),
        ),
    ]
