# Generated by Django 6.0.6 on 2026-06-22 09:11

import django.core.validators
import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0027_productgalleryimagemodel_sort_order"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productgalleryimagemodel",
            name="caption",
            field=wagtail.fields.RichTextField(
                blank=True,
                help_text="Comment to the product",
                max_length=80,
                null=True,
                validators=[
                    django.core.validators.MaxLengthValidator(80),
                    django.core.validators.RegexValidator(
                        regex="^[A-Za-z0-9\\. \\\"'_%+-]*$"
                    ),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="productgalleryimagemodel",
            name="product_characteristic",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                related_query_name="product_characteristics_related",
                to="catalog.productcharacteristics",
            ),
        ),
    ]
