# Generated by Django 6.0.6 on 2026-06-22 09:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0028_alter_productgalleryimagemodel_caption_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productgalleryimagemodel",
            name="product_characteristic",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="characteristics",
                related_query_name="product_characteristics_related",
                to="catalog.productcharacteristics",
            ),
        ),
    ]
