# Generated by Django 6.0.6 on 2026-06-22 09:44

import django.db.models.deletion
import modelcluster.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0029_alter_productgalleryimagemodel_product_characteristic"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="productgalleryimagemodel",
            name="product_characteristic",
        ),
        migrations.AddField(
            model_name="productcharacteristics",
            name="product",
            field=modelcluster.fields.ParentalKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="characteristics",
                to="catalog.productgalleryimagemodel",
            ),
        ),
    ]
