# Generated by Django 6.0.6 on 2026-06-22 09:53

import django.core.validators
import django.db.models.deletion
import modelcluster.fields
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "catalog",
            "0030_remove_productgalleryimagemodel_product_characteristic_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="productcharacteristics",
            name="name",
            field=models.CharField(
                db_index=True,
                help_text="The name of the property",
                max_length=80,
                validators=[
                    django.core.validators.MinLengthValidator(3),
                    django.core.validators.MaxLengthValidator(80),
                    django.core.validators.RegexValidator("^[\\w \\-_]{3,80}$"),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="productcharacteristics",
            name="product",
            field=modelcluster.fields.ParentalKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="properties",
                to="catalog.productgalleryimagemodel",
            ),
        ),
        migrations.AlterField(
            model_name="productcharacteristics",
            name="value",
            field=models.CharField(
                default="-",
                help_text="The value of the property",
                max_length=10,
                validators=[django.core.validators.MaxLengthValidator(10)],
            ),
        ),
        migrations.AlterField(
            model_name="productgalleryimagemodel",
            name="caption",
            field=wagtail.fields.RichTextField(
                blank=True,
                help_text="Comment to the product",
                max_length=80,
                null=True,
                validators=[
                    django.core.validators.MaxLengthValidator(80),
                    django.core.validators.RegexValidator(
                        regex="^[A-Za-z0-9\\. \\\"'_%+-]{0,80}$"
                    ),
                ],
            ),
        ),
    ]
