# Generated by Django 6.0.6 on 2026-06-22 10:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0031_alter_productcharacteristics_name_and_more"),
        ("wagtailimages", "0027_image_description"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="oneimagemodels",
            options={
                "ordering": ["-image"],
                "verbose_name": "Image",
                "verbose_name_plural": "Images",
            },
        ),
        migrations.AlterField(
            model_name="oneimagemodels",
            name="image",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                related_query_name="image_%(app_label)s_%(class)s_related",
                to="wagtailimages.image",
            ),
        ),
        migrations.AlterModelTable(
            name="oneimagemodels",
            table="images",
        ),
    ]
