# Generated by Django 6.0.6 on 2026-06-22 10:11

import django.core.validators
import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0032_alter_oneimagemodels_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productgalleryimagemodel",
            name="caption",
            field=wagtail.fields.RichTextField(
                blank=True,
                help_text="Comment to the product",
                max_length=80,
                null=True,
                validators=[
                    django.core.validators.MaxLengthValidator(80),
                    django.core.validators.RegexValidator(
                        regex="^[\\.>< \\/ \\w \\\"'_%+-]{0,80}$"
                    ),
                ],
            ),
        ),
    ]
