# Generated by Django 6.0.6 on 2026-06-22 10:16

import django.core.validators
import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0033_alter_productgalleryimagemodel_caption"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productgalleryimagemodel",
            name="caption",
            field=wagtail.fields.RichTextField(
                blank=True,
                help_text="Comment to the product",
                max_length=80,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        regex="^[\\.>< =\\\"\\'\\/ \\w \\\"'_%+-]+$"
                    )
                ],
            ),
        ),
    ]
