# Generated by Django 6.0.6 on 2026-06-28 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0034_alter_productgalleryimagemodel_caption"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="brandmodel",
            options={"ordering": ("name",), "verbose_name": "Brand"},
        ),
        migrations.AlterModelOptions(
            name="categorymodel",
            options={"ordering": ("name",), "verbose_name": "Category"},
        ),
        migrations.AlterModelTable(
            name="productgalleryimagemodel",
            table="product_gallery",
        ),
    ]
