# Generated by Django 6.0.6 on 2026-06-30 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "catalog",
            "0035_alter_brandmodel_options_alter_categorymodel_options_and_more",
        ),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="productmodel",
            unique_together={("name", "brand"), ("name", "category")},
        ),
    ]
