# Generated by Django 6.0.6 on 2026-07-01 03:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0036_alter_productmodel_unique_together"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="productcharacteristics",
            name="product",
        ),
        migrations.RemoveField(
            model_name="productmodel",
            name="attributes",
        ),
    ]
