# Generated by Django 6.0.6 on 2026-07-01 03:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0037_remove_productcharacteristics_product_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="productmodel",
            name="attributes",
            field=models.ForeignKey(
                blank=True,
                help_text="Commons characteristics of the ont product.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="catalog.productcharacteristics",
                verbose_name="+",
            ),
        ),
    ]
