# Generated by Django 6.0.6 on 2026-07-01 04:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0041_remove_productmodel_attributes_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productcharacteristics",
            name="attributes",
            field=models.ForeignKey(
                blank=True,
                help_text="Commons characteristics of the ont product.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="attributes",
                to="catalog.productmodel",
                verbose_name="Product Characteristics",
            ),
        ),
    ]
