# Generated by Django 6.0.6 on 2026-07-01 04:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0042_alter_productcharacteristics_attributes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="oneimagemodels",
            name="product",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="images",
                to="catalog.productmodel",
            ),
        ),
    ]
