# Generated by Django 6.0.6 on 2026-07-01 05:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0046_alter_oneimagemodels_product"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productmodel",
            name="attributes",
            field=models.ForeignKey(
                blank=True,
                help_text="Commons characteristics of the ont product.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="attributes",
                related_query_name="product_%(app_label)s_%(class)s_Characteristics",
                to="catalog.productcharacteristics",
                verbose_name="Product Characteristics",
            ),
        ),
    ]
