# Generated by Django 6.0.6 on 2026-07-01 07:40

import django.db.models.deletion
import modelcluster.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0054_alter_productcharacteristics_product"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productcharacteristics",
            name="product",
            field=modelcluster.fields.ParentalKey(
                blank=True,
                help_text="Commons characteristics of the ont product.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="characteristics",
                to="catalog.productmodel",
                verbose_name="product Characteristics",
            ),
        ),
    ]
