# Generated by Django 6.0.6 on 2026-07-01 08:37

import django.core.validators
import django.db.models.deletion
import modelcluster.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0055_alter_productcharacteristics_product"),
    ]

    operations = [
        migrations.AlterField(
            model_name="oneimagemodels",
            name="product",
            field=modelcluster.fields.ParentalKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="images",
                related_query_name="product_%(app_label)s_%(class)s_related",
                to="catalog.productmodel",
            ),
        ),
        migrations.AlterField(
            model_name="oneimagemodels",
            name="title",
            field=models.CharField(
                help_text="The title of the schematic. Available char: 'A-Za-z0-9\\. \\\"'_%+-'",
                max_length=100,
                unique=True,
                validators=[
                    django.core.validators.MaxLengthValidator(100),
                    django.core.validators.MinLengthValidator(3),
                    django.core.validators.RegexValidator(
                        regex="^[A-Za-zА-ЯЪа-яъ0-9\\. \\\"'_%+-]+$"
                    ),
                ],
                verbose_name="Title",
            ),
        ),
    ]
