# Generated by Django 6.0.6 on 2026-07-08 07:44

from decimal import Decimal

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0056_alter_oneimagemodels_product_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="productmodel",
            name="product_discount",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                max_digits=12,
                validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
                verbose_name="Product Discount on the order moment",
            ),
        ),
        migrations.AddField(
            model_name="productmodel",
            name="product_sku",
            field=models.CharField(
                blank=True,
                db_index=True,
                default="",
                max_length=100,
                verbose_name="Product SKU",
            ),
        ),
        migrations.AlterField(
            model_name="productmodel",
            name="name",
            field=models.CharField(
                help_text="The name of the product",
                max_length=80,
                unique=True,
                validators=[
                    django.core.validators.MinLengthValidator(3),
                    django.core.validators.MaxLengthValidator(80),
                ],
                verbose_name="Product Name",
            ),
        ),
        migrations.AlterField(
            model_name="productmodel",
            name="price",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="The price of the product",
                max_digits=12,
                validators=[
                    django.core.validators.MinValueValidator(Decimal("0.00")),
                    django.core.validators.DecimalValidator(
                        decimal_places=2, max_digits=10
                    ),
                ],
                verbose_name="Product Price on the order moment",
            ),
        ),
    ]
