# Generated by Django 6.0.6 on 2026-07-09 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0057_productmodel_product_discount_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productmodel",
            name="stock_quantity",
            field=models.PositiveIntegerField(
                db_index=True, default=0, help_text="The quantity of the product"
            ),
        ),
    ]
