# Generated by Django 6.0.6 on 2026-07-09 08:52

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0059_alter_productgalleryimagemodel_product_and_more"),
        ("profiles", "0007_userprofile_product"),
    ]

    operations = [
        migrations.AddField(
            model_name="productmodel",
            name="profile",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="items",
                to="profiles.userprofile",
                verbose_name="Profile",
            ),
        ),
        migrations.AlterField(
            model_name="productmodel",
            name="product_sku",
            field=models.CharField(
                db_index=True,
                help_text="The required unique SKU/code/name of the product",
                max_length=100,
                unique=True,
                validators=[
                    django.core.validators.MinLengthValidator(3),
                    django.core.validators.MaxLengthValidator(100),
                    django.core.validators.RegexValidator(
                        message="Only letters, numbers and underscores are allowed.",
                        regex="(^[a-zA-Z0-9_\\-]+$)",
                    ),
                ],
                verbose_name="Product SKU",
            ),
        ),
    ]
