# Generated by Django 6.0.6 on 2026-07-10 02:12

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0060_productmodel_profile_alter_productmodel_product_sku"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="productmodel",
            name="profile",
        ),
        migrations.AlterField(
            model_name="productgalleryimagemodel",
            name="product",
            field=models.ForeignKey(
                limit_choices_to={"is_active": True},
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                related_query_name="product_related",
                to="catalog.productmodel",
            ),
        ),
        migrations.AlterField(
            model_name="productmodel",
            name="product_sku",
            field=models.CharField(
                db_index=True,
                help_text="The required unique SKU/code/name of the product",
                max_length=100,
                unique=True,
                validators=[
                    django.core.validators.MinLengthValidator(3),
                    django.core.validators.MaxLengthValidator(100),
                    django.core.validators.RegexValidator(
                        message="Only letters, numbers and underscores are allowed.",
                        regex="^[a-zA-Z0-9_\\-]+$",
                    ),
                ],
                verbose_name="Product SKU",
            ),
        ),
    ]
