# Generated by Django 6.0.6 on 2026-07-12 01:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0061_remove_productmodel_profile_and_more"),
        ("profiles", "0009_userprofilemodel"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productgalleryimagemodel",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                help_text="THe user who created the position",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(app_label)s_%(class)s_product_characteristics_created",
                to="profiles.userprofilemodel",
            ),
        ),
        migrations.AlterField(
            model_name="productgalleryimagemodel",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                help_text="The user who last updated the position",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(app_label)s_%(class)s_product_characteristics_updated",
                to="profiles.userprofilemodel",
            ),
        ),
        migrations.AlterField(
            model_name="productmodel",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                help_text="THe user who created the position",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(app_label)s_%(class)s_product_characteristics_created",
                to="profiles.userprofilemodel",
            ),
        ),
        migrations.AlterField(
            model_name="productmodel",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                help_text="The user who last updated the position",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(app_label)s_%(class)s_product_characteristics_updated",
                to="profiles.userprofilemodel",
            ),
        ),
    ]
