# Generated by Django 6.0.6 on 2026-07-13 05:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0062_alter_productgalleryimagemodel_created_by_and_more"),
        ("profiles", "0009_userprofilemodel"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productgalleryimagemodel",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                db_comment="This is a user's profile created position. Just that is goes not to the direct user. That is go to\n        the profile user: 'UserProfileManagerModel' =>         'profiles.models.model_<client | admin | editor | manager | client| moderator >' =>         'wagtail.users.models.UserProfile' => 'persons.models.Users' model.\n        If need  a direct user mean we get of user through the 'ProfilesModel' model..\n        ",
                help_text="THe user who created the position",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(app_label)s_%(class)s_product_characteristics_created",
                to="profiles.userprofilemodel",
            ),
        ),
        migrations.AlterField(
            model_name="productgalleryimagemodel",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                db_comment="This is a user last updated position.\n        If need a direct user mean we act by analogy the 'self.created_by ",
                help_text="The user who last updated the position",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(app_label)s_%(class)s_product_characteristics_updated",
                to="profiles.userprofilemodel",
            ),
        ),
        migrations.AlterField(
            model_name="productmodel",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                db_comment="This is a user's profile created position. Just that is goes not to the direct user. That is go to\n        the profile user: 'UserProfileManagerModel' =>         'profiles.models.model_<client | admin | editor | manager | client| moderator >' =>         'wagtail.users.models.UserProfile' => 'persons.models.Users' model.\n        If need  a direct user mean we get of user through the 'ProfilesModel' model..\n        ",
                help_text="THe user who created the position",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(app_label)s_%(class)s_product_characteristics_created",
                to="profiles.userprofilemodel",
            ),
        ),
        migrations.AlterField(
            model_name="productmodel",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                db_comment="This is a user last updated position.\n        If need a direct user mean we act by analogy the 'self.created_by ",
                help_text="The user who last updated the position",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(app_label)s_%(class)s_product_characteristics_updated",
                to="profiles.userprofilemodel",
            ),
        ),
    ]
