# Generated by Django 6.0.6 on 2026-06-10 10:27

import django.contrib.auth.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("persons", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="users",
            name="email",
            field=models.EmailField(
                max_length=150,
                unique=True,
                validators=[
                    django.core.validators.MaxLengthValidator(150),
                    django.core.validators.MinLengthValidator(5),
                    django.core.validators.EmailValidator(),
                ],
                verbose_name="email address",
            ),
        ),
        migrations.AlterField(
            model_name="users",
            name="is_sent",
            field=models.BooleanField(
                default=False,
                help_text="Part is registration of new user.It is message sending to user's email. User indicates his email at the registrations moment.",
                verbose_name="Message was sent",
            ),
        ),
        migrations.AlterField(
            model_name="users",
            name="password",
            field=models.CharField(
                max_length=255,
                validators=[django.core.validators.MinLengthValidator(7)],
                verbose_name="password",
            ),
        ),
        migrations.AlterField(
            model_name="users",
            name="username",
            field=models.CharField(
                error_messages={"unique": "A user with that username already exists."},
                help_text="Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.",
                max_length=150,
                unique=True,
                validators=[
                    django.core.validators.MinLengthValidator(2),
                    django.core.validators.MaxLengthValidator(50),
                    django.contrib.auth.validators.UnicodeUsernameValidator(),
                ],
                verbose_name="username",
            ),
        ),
    ]
