# Generated by Django 6.0.6 on 2026-06-16 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("persons", "0002_alter_users_email_alter_users_is_sent_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="users",
            name="category",
        ),
    ]
