# Generated by Django 6.0.6 on 2026-07-07 00:48

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0001_initial"),
        ("catalog", "0056_alter_oneimagemodels_product_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CartOrderModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="OrderItemModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.CharField(max_length=100)),
                (
                    "image",
                    models.CharField(
                        validators=[
                            django.core.validators.RegexValidator(
                                regex="(media\\/[a-zA-Z0-9_\\-\\/]+/)$"
                            )
                        ]
                    ),
                ),
                ("quantity", models.PositiveIntegerField(default=0)),
                ("cost", models.PositiveIntegerField(default=0)),
                ("is_paid", models.BooleanField(default=False)),
                (
                    "index_product",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="catalog.productmodel",
                    ),
                ),
            ],
            options={
                "verbose_name": "Cart",
                "verbose_name_plural": "Carts",
                "db_table": "cart",
                "ordering": ["-quantity", "-cost"],
                "indexes": [
                    models.Index(
                        fields=["index_product", "cost", "is_paid"],
                        name="cart_index_p_a0cf8d_idx",
                    )
                ],
                "unique_together": {("index_product",)},
            },
        ),
    ]
