# Generated by Django 6.0.6 on 2026-07-09 03:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0057_productmodel_product_discount_and_more"),
        ("profiles", "0006_userprofile"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="product",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="product",
                to="catalog.productmodel",
                verbose_name="Product",
            ),
        ),
    ]
