# Generated by Django 6.0.6 on 2026-07-17 10:42

from decimal import Decimal

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("catalog", "0003_initial"),
        ("orders", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="OrderModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "profile",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Profile ID"
                    ),
                ),
                (
                    "customer_email",
                    models.EmailField(
                        blank=True,
                        db_index=True,
                        max_length=254,
                        null=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                regex="^[a-zA-Z0-9!#$%&\\'*+/=?^_`{|}~-]+(?:\\.[a-zA-Z0-9!#$%&\\'*+/=?^_`{|}~-]+)*@(?:[a-zA-Z0-9](?:[a-zA-Z0-9-]*[a-zA-Z0-9])?\\.)+[a-zA-Z0-9](?:[a-zA-Z0-9-][a-zA-Z0-9]?)?$"
                            ),
                            django.core.validators.EmailValidator(),
                        ],
                        verbose_name="Customer Email",
                    ),
                ),
                (
                    "customer_phone",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        validators=[
                            django.core.validators.RegexValidator(
                                regex="^(\\+?\\d{1,3}[\\s\\-]?)?\\(?\\d{2,5}\\)?[\\s\\-]?\\d{3,4}[\\s\\-]?\\d{3,4}$"
                            ),
                            django.core.validators.MaxLengthValidator(20),
                        ],
                        verbose_name="Customer Phone",
                    ),
                ),
                (
                    "customer_name",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        validators=[
                            django.core.validators.RegexValidator(
                                regex="(^[A-ZА-ЯЁ][a-zа-яё]+(?:[-\\s][A-ZА-ЯЁ][a-zа-яЁ]+)*)$"
                            ),
                            django.core.validators.MaxLengthValidator(50),
                            django.core.validators.MinLengthValidator(5),
                        ],
                        verbose_name="Name of client",
                    ),
                ),
                ("shipping_address", models.TextField(verbose_name="Address")),
                ("shipping_city", models.CharField(verbose_name="City")),
                (
                    "shipping_country",
                    models.CharField(default="Russia", verbose_name="Country"),
                ),
                (
                    "subtotal",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                        verbose_name="Amount without discount",
                    ),
                ),
                (
                    "discount",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                        verbose_name="Discount",
                    ),
                ),
                (
                    "shipping_cost",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                        verbose_name="Shipping cost",
                    ),
                ),
                (
                    "tax",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                        verbose_name="Tax",
                    ),
                ),
                (
                    "total",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                        verbose_name="Total sum",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending pay"),
                            ("paid", "Paid"),
                            ("processing", "In processing"),
                            ("shipped", "Shipped"),
                            ("delivered", "Delivered"),
                            ("cancelled", "Cancelled"),
                            ("refunded", "Refunded"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                        verbose_name="Status payment",
                    ),
                ),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("card", "Card"),
                            ("paypal", "PayPal"),
                            ("crypto", "Crypto"),
                            ("bank", "Bank"),
                            ("cash", "Many upon receipt"),
                            ("robokassa", "Robokassa"),
                            ("UMoney", "ЮMoney"),
                        ],
                        default="bank",
                        max_length=20,
                        verbose_name="Payment Method",
                    ),
                ),
                (
                    "payment_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("success", "Success"),
                            ("failed", "Failed"),
                            ("refunded", "Refunded"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                        verbose_name="Payment Method",
                    ),
                ),
                (
                    "payment_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        max_length=20,
                        verbose_name="Payment ID",
                    ),
                ),
                (
                    "payment_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Payment Date"
                    ),
                ),
                (
                    "comment",
                    models.TextField(blank=True, null=True, verbose_name="Comment"),
                ),
                (
                    "admin_comment",
                    models.TextField(
                        blank=True, null=True, verbose_name="Admin comment"
                    ),
                ),
                (
                    "tracking_number",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        max_length=100,
                        verbose_name="Tracking Number",
                    ),
                ),
                (
                    "delivery_company",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Delivery Company"
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="IP Address of client"
                    ),
                ),
                ("user_aget", models.TextField(blank=True, verbose_name="User-Aget")),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        verbose_name="Created Date",
                    ),
                ),
                (
                    "update_at",
                    models.DateTimeField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        verbose_name="Updated Date",
                    ),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        null=True,
                        verbose_name="Completed Date",
                    ),
                ),
            ],
            options={
                "verbose_name": "Order",
                "verbose_name_plural": "Orders",
                "db_table": "orders",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["status", "created_at"], name="orders_status_11db6c_idx"
                    ),
                    models.Index(
                        fields=["payment_status", "created_at"],
                        name="orders_payment_c29932_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="OrderLogModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "old_status",
                    models.CharField(
                        blank=True, default="", max_length=20, verbose_name="Old status"
                    ),
                ),
                (
                    "new_status",
                    models.CharField(
                        blank=True, default="", max_length=20, verbose_name="New status"
                    ),
                ),
                (
                    "comment",
                    models.TextField(blank=True, default="", verbose_name="Comment"),
                ),
                (
                    "create_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Create at"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="order_logs",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="logs",
                        to="orders.ordermodel",
                        verbose_name="Order",
                    ),
                ),
            ],
            options={
                "verbose_name": "Log a history of order",
                "verbose_name_plural": "Logs a history of orders",
                "db_table": "order_log",
                "ordering": ["-create_at"],
            },
        ),
        migrations.CreateModel(
            name="OrderItemModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantity",
                    models.PositiveIntegerField(
                        default=1,
                        help_text="The quantity of the product",
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="Quantity",
                    ),
                ),
                (
                    "subtotal",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                        verbose_name="Subtotal",
                    ),
                ),
                (
                    "total",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                        verbose_name="Total",
                    ),
                ),
                (
                    "options",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Example: {'color': 'red', 'size': 'M'}",
                        verbose_name="Options of the one product",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "product",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="order_items",
                        to="catalog.productmodel",
                        verbose_name="Product",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="orders.ordermodel",
                        verbose_name="Order",
                    ),
                ),
            ],
            options={
                "verbose_name": "Order Item",
                "verbose_name_plural": "Order Items",
                "db_table": "order_item",
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="PaymentModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                        verbose_name="Amount",
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        choices=[("RUB", "Rub"), ("EUR", "EUR"), ("DOL", "Dollar")],
                        default="RUB",
                        max_length=3,
                        verbose_name="Currency",
                    ),
                ),
                (
                    "method",
                    models.CharField(
                        choices=[
                            ("card", "Card"),
                            ("paypal", "PayPal"),
                            ("crypto", "Crypto"),
                            ("bank", "Bank"),
                            ("cash", "Many upon receipt"),
                            ("robokassa", "Robokassa"),
                            ("UMoney", "ЮMoney"),
                        ],
                        default="card",
                        max_length=20,
                        verbose_name="Payment Method",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("success", "Success"),
                            ("failed", "Failed"),
                            ("refunded", "Refunded"),
                            ("canceled", "Canceled"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                        verbose_name="Payment Status",
                    ),
                ),
                (
                    "payment_id",
                    models.CharField(
                        db_index=True,
                        max_length=255,
                        unique=True,
                        verbose_name="Payment ID",
                    ),
                ),
                (
                    "provider",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Example: YooKassa, Stripe, Robokassa",
                        max_length=50,
                        verbose_name="Provide of payment",
                    ),
                ),
                (
                    "card_last4",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=4,
                        verbose_name="Card Last 4 numbers",
                    ),
                ),
                (
                    "card_brand",
                    models.CharField(
                        blank=True, default="", max_length=20, verbose_name="Card Brand"
                    ),
                ),
                (
                    "request_data",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Request Data"
                    ),
                ),
                (
                    "response_data",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Response Data"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Created at"
                    ),
                ),
                (
                    "paid_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="Paid at"),
                ),
                (
                    "refunded_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Refunded at"
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payments",
                        to="orders.ordermodel",
                        verbose_name="Order",
                    ),
                ),
            ],
            options={
                "verbose_name": "Payment",
                "verbose_name_plural": "Payments",
                "db_table": "order_payment",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["order", "status"],
                        name="order_payme_order_i_6b4675_idx",
                    ),
                    models.Index(
                        fields=["payment_id"], name="order_payme_payment_184bd4_idx"
                    ),
                ],
            },
        ),
    ]
