# Generated by Django 6.0.6 on 2026-07-08 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="orderitemmodel",
            name="product_discount",
        ),
        migrations.RemoveField(
            model_name="orderitemmodel",
            name="product_name",
        ),
        migrations.RemoveField(
            model_name="orderitemmodel",
            name="product_price",
        ),
        migrations.RemoveField(
            model_name="orderitemmodel",
            name="product_sku",
        ),
    ]
