# Generated by Django 6.0.6 on 2026-07-10 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0002_remove_orderitemmodel_product_discount_and_more"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="ordermodel",
            name="orders_profile_602e0e_idx",
        ),
        migrations.AlterField(
            model_name="ordermodel",
            name="profile",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="Profile ID"
            ),
        ),
    ]
